### ISSUE TITLE
Make the project truly open-source

### ISSUE THREAD

**Issue by hayop77300** [MELDProject/meld_classifier#51]
Hello MELD team,

The project seems very cool, however it seems impossible to play wit its own MRI data without having a model dataset === having an access to lots of EEG records other patients to build a model.

In my opinion, no law would be broken in case you publish the model build on a patient's data publicly in this or in the separate repository so all people could try the project without contacting or being locked on a medical universities. Probably several models should be published per specific MRI scanner I guess. As an example OpenAI company - they harvested data from all over the world and everything is fine so far. Could we give a possibility to every individual to run the project it would help for the project development overall.

**Comment by hayop77300** [comment]
Sorry, I had issues with my account, so commenting here to make sure repo owners get notification about the issue.

**Comment by hayop77300** [comment]
Sorry, I had issues with my account, so commenting here to make sure repo owners get notification about the issue.

/cc @kwagstyl

**Comment by kwagstyl** [comment]
Thank you for these suggestions. MELD is committed to being open, whilst following our agreements with partner sites and ethical guidelines. The current way to access the MELD dataset is through submitting a project proposal to the MELD consortium.
